name: Check MOM6 test data is accessible

on: [push]

jobs:
  check-ftp-access:

    runs-on: ubuntu-latest

    steps:
    - name: Compile with openMP
      run: wget ftp://ftp.gfdl.noaa.gov/perm/Alistair.Adcroft/MOM6-testing/Baltic_OM4_05.tgz
