name: Check MOM6 test data is accessible

on:
  push:
  schedule:
    - cron:  '15 3 * * *'

jobs:
  check-ftp-access:

    runs-on: ubuntu-latest

    steps:
    - name: wget data
      run: wget ftp://ftp.gfdl.noaa.gov/perm/Alistair.Adcroft/MOM6-testing/Baltic_OM4_05.tgz

    - name: check data
      run: md5sum Baltic_OM4_05.tgz

    - name: status
      run: ls -l Baltic_OM4_05.tgz
